CREATE  TABLE IF NOT EXISTS GREETING (
	id		 INT NOT NULL AUTO_INCREMENT ,
	book		 VARCHAR(100) NOT NULL ,
	authorId	 VARCHAR(100) NULL ,
	authorEmail	 VARCHAR(100) NULL ,
	content		 VARCHAR(200) NOT NULL ,
	created		 TIMESTAMP ,
	PRIMARY KEY (id) 
) ENGINE = InnoDB;
